---
pull_request_rules:
  - name: Automatic merge
    conditions:
      - and:
          - or:
              - "#approved-reviews-by>=1"
              - author=JohnStrunk
              - author=renovate-bot
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success="Successful CI"
      - check-success=DCO
      - check-success="Build docs"
    actions:
      merge:
        method: merge
