
pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
queue_rules:
  - name: duplicated default from Automatic merge trusted PRs
    queue_conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success="Successful CI"
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
      - and:
          - or:
              - author=JohnStrunk
              - author=renovate-bot
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success="Successful CI"
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
    merge_conditions: []
    merge_method: merge
    method: merge
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success="Successful CI"
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success="Successful CI"
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
    merge_method: merge
