---
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success="Successful CI"
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
    actions:
      queue:
        method: merge
        name: default

  - name: Automatic merge trusted PRs
    conditions:
      - and:
          - or:
              - author=JohnStrunk
              - author=renovate-bot
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success="Successful CI"
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
    actions:
      queue:
        method: merge
        name: default

queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success="Successful CI"
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
