---
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success="Successful CI"
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
      - check-success=SonarCloud Code Analysis
    actions:
      queue:
        method: merge
        name: default

  - name: Automatic merge own PRs
    conditions:
      - author=JohnStrunk
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success="Successful CI"
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
      - check-success=SonarCloud Code Analysis
    actions:
      queue:
        method: merge
        name: default

queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success="Successful CI"
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
      - check-success=SonarCloud Code Analysis
