---
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success=Test
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
    actions:
      merge:
        method: merge
        strict: true

  - name: Automatic merge own PRs
    conditions:
      - author=JohnStrunk
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success=Test
      - check-success=DCO
      - check-success=docs/readthedocs.org:wahoo-results
    actions:
      merge:
        method: merge
        strict: true