---
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install pipenv
      - pipenv requirements --categories docs > docs/requirements.txt
    post_build:
      # Override the default sitemap.xml with a custom one that we refer to from
      # our custom robots.txt
      - cp "$READTHEDOCS_OUTPUT/html/sitemap.xml"
        "$READTHEDOCS_OUTPUT/html/sitemap-custom.xml"
      - cat "$READTHEDOCS_OUTPUT/html/sitemap-custom.xml"

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt
