---
# yamllint disable rule:line-length

name: Automatically add items to project tracking board

on:  # yamllint disable-line rule:truthy
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add item to project board
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/add-to-project
      - uses: actions/add-to-project@31b3f3ccdc584546fc445612dec3f38ff5edb41c  # v0.5.0
        with:
          project-url: https://github.com/users/JohnStrunk/projects/2
          # PAT needs repo & project scope
          github-token: ${{ secrets.PAT_ADD_TO_PROJECT }}
